language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run deploy:prod-quick
deploy:
  - provider: firebase
    token:
      secure: IRggHK6aoMoO5SC+xqjjz1qaSUnhQulhaXV2u+zFJOidFh/KcG4AfuACQINidWa+5q7Rxwq+roBz08sozgOmNQ6wgleLIHIj7D7nIgz351QbvY2o+0LM/Gjd0nC3gVK1I6H3Hy8ikFlH2K1UYSrbq9KL4r4TWVAWLUG4fbPw4ZNaqtEpIA6cCx+PZKClxB+CUq/EPbNpB4s/YCWnNbG1yfJvYcxZajYAG4W1urLAjGPpx52hlwUB6mXldSOWZLpya7QalbYdG5Ofi0VWMqeo6/g1IYWJPtqZ+Dz6f8LG/KYUSb39n7VamePC/HoYPI6gSBe2P2rDV+83qoXZMCZ+HTmaIz6PXVXvHUZWYfbKzrc85XsqevJJ4pjKvWl5c9fej+oS5sBu/U6lGJWwY6AR80IakfCOeSQ3X2l77JqvUi7z9LdwPZmj25cSDH7xrllAFO+joCKDqm/t0u3g3XEPNKEbOMZrYVBooXGt6liDAZ53Y7P0DqbTnsuR5BW6JGkVhgXtNlKC4+ljojvy5FoS/N4CKrhWmBCJVMYO5P6p4t0MaYVjOLh+Qov5dABrxvV1XxLE5YPiNLfN9SusMiMuFFe1P1GNpAP6y3uQfe7uZnnD1wp3tadM3JvNLuX96cCcvc8t8rmOBtH8dAumSW0D9a8bB9O+9JSp7BLL4Zz7jnY=
    project: dev-geoweb-meteo-fi
    skip_cleanup: true
    on:
      branch: devel
  - provider: firebase
    token:
      secure: IRggHK6aoMoO5SC+xqjjz1qaSUnhQulhaXV2u+zFJOidFh/KcG4AfuACQINidWa+5q7Rxwq+roBz08sozgOmNQ6wgleLIHIj7D7nIgz351QbvY2o+0LM/Gjd0nC3gVK1I6H3Hy8ikFlH2K1UYSrbq9KL4r4TWVAWLUG4fbPw4ZNaqtEpIA6cCx+PZKClxB+CUq/EPbNpB4s/YCWnNbG1yfJvYcxZajYAG4W1urLAjGPpx52hlwUB6mXldSOWZLpya7QalbYdG5Ofi0VWMqeo6/g1IYWJPtqZ+Dz6f8LG/KYUSb39n7VamePC/HoYPI6gSBe2P2rDV+83qoXZMCZ+HTmaIz6PXVXvHUZWYfbKzrc85XsqevJJ4pjKvWl5c9fej+oS5sBu/U6lGJWwY6AR80IakfCOeSQ3X2l77JqvUi7z9LdwPZmj25cSDH7xrllAFO+joCKDqm/t0u3g3XEPNKEbOMZrYVBooXGt6liDAZ53Y7P0DqbTnsuR5BW6JGkVhgXtNlKC4+ljojvy5FoS/N4CKrhWmBCJVMYO5P6p4t0MaYVjOLh+Qov5dABrxvV1XxLE5YPiNLfN9SusMiMuFFe1P1GNpAP6y3uQfe7uZnnD1wp3tadM3JvNLuX96cCcvc8t8rmOBtH8dAumSW0D9a8bB9O+9JSp7BLL4Zz7jnY=
    project: staging-geoweb-meteo-fi
    skip_cleanup: true
    on:
      branch: staging
  - provider: firebase
    token:
      secure: "illKUTbyY6o9VxhgK957WMA/ZGxNZqXTXhIe4PtzQItSD5YGHzXgUdSU4fBo6sZqbY1L1LSnTivjLGzKz5O7e6g6LNN0+96kPP1spCJOqi14y/qvjEuMxLZyMkXkuH5yCJrBmzZNgfjC5/nkN1bBeAK/qHl8PG9yZIIl8IamVkiN2hWItxWuYHw0mJnd/zAov4TAK96EQdjXe65a6MFEZz+IfWcyq4rcb2AXmtrefExG5xPdetpHkYXQOe3sjimqVGzwOobDzlXj0PwvwQxp21IsQo1x1ghM5psWhl9oDtCuUNLk/nbUaNrdpCXwOshrtUuCfkja7TCBVrY+W7m2s4/aF3l0Oo6JX+B3QIxr/gfyj2izWRSv1zTP3xOvsHj6vdAzlP/rHBQqHbofHFchaeOfGIFhqyuAf2bCg308tvt0FkXIxS8Odmae23t29NL86T4tSowk4FRf0BQ5A6GH2rbSn4anAJB9KMHjRU96Ii8515vcLX8WSL63E50jvEqnVfEF3kmcPPBDMuPOiFf8o9jRQmlBOx81LGUatRkICNYV3TZ3tRA7SI6B4X3rmINZuCqeBTil42kSWkwWuw+U4yaUY2v8sQCRv23DYtXSveEmQdnp6LJffhS/00JSQUQAWJGHFNRthXJalhTgQAatCZOgr8sJFovVfGRlMTi11IQ="
    project: geoweb-meteo-fi
    skip_cleanup: true
    on:
      branch: master
